[tool.poetry]
name = "core"
version = "1.0.0"
description = "Common Operations for Robust Engineering"
authors = [
      "François Steinmetz",
      "Joackim Orcière",
      "Nathan Capon",
]

Homepage = "https://github.com/hygeos/core"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]

exclude = [
    "misc",
    "__pycache__",
    "*__pycache__*",
]

[tool.poetry.dependencies]
tqdm = "*" # tqdm itself doesn't have any dependencies

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]

addopts = [
    "-s" # show the captured output on successful tests
]